### ISSUE TITLE
Change color of the "Quickstart" primary button

### ISSUE THREAD

**Issue by mirca** [barentsen/amunra-sphinx-theme#7]
Yo @barentsen, I was thinking to propose changing the color of the "Quickstart" button in the front page.  My feeling is that a grey color would fit better the overall minimalist theme, what do you think?

Here is more or less what I was thinking:
<img width="651" alt="Screenshot 2020-05-28 at 5 51 24 PM" src="https://user-images.githubusercontent.com/13077051/83127025-3b03b680-a10c-11ea-9646-9cc9737598d2.png">

And when you hover the mouse over the button:
<img width="666" alt="Screenshot 2020-05-28 at 5 51 34 PM" src="https://user-images.githubusercontent.com/13077051/83127033-3ccd7a00-a10c-11ea-9bb8-5ac401e2cc5c.png">

What's your feeling about this?

Thanks!

**Comment by barentsen** [comment]
The bright blue color of the button is intentional, because it helps users understand the next action they should take!

Your issue does make me realize that it should be easier for users to override the CSS, which I fixed in https://github.com/barentsen/amunra-sphinx-theme/pull/8.

To make the quickstart button gray, you can now do the following:

1. Add this line to `conf.py`:
```python
html_css_files = ['custom.css']
```

2. Create a file called `_static/custom.css` containing the following css:
```css
.btn-primary {
    background-color: #aaaaaa;
    border-color: #aaaaaa;
}
```

Now run `make clean` and `make html`, and the button should be gray.  #AAAAAAH!

Changing the color when you hover the mouse is an exercise for the reader!
